SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR tcp ;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;

SELECT DEPARTMENT_NAME "학과 명" , CATEGORY"계열"
FROM TB_DEPARTMENT ;

SELECT DEPARTMENT_NAME"의 정원은", LENGTH(DEPARTMENT_NAME)"명 입니다"
FROM TB_DEPARTMENT;


SELECT STUDENT_NAME
FROM  TB_STUDENT ts ;
WHERE EMP_



