ALTER SESSION SET "_ORACLE_SCRIPT" =TRUE;

CREATE USER KH_SHOP IDENTIFIED BY 1234;

GRANT CREATE SESSION TO KH_SHOP;--접속권한 부여
GRANT CREATE TABLE TO KH_SHOP; --테이블 생성권한 부여
ALTER USER KH_SHOP DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
--테이블 
GRANT CONNECT , RESOURCE TO KH_SHOP;

--1
CREATE TABLE CATEGORIES(
CATEGORY_ID NUMBER PRIMARY KEY,
CATEGORY_NAME VARCHAR2(100)UNIQUE
);
COMMENT ON COLUMN CATEGORIES.CATEGORY_ID IS '카테고리 ID';
COMMENT ON COLUMN CATEGORIES.CATEGORY_NAME IS '카테고리 이름';

SELECT * FROM CATEGORIES;
INSERT INTO CATEGORIES(CATEGORY_ID,CATEGORY_NAME) VALUES (1,'스마트폰');
INSERT INTO CATEGORIES(CATEGORY_ID,CATEGORY_NAME) VALUES (2,'TV');
INSERT INTO CATEGORIES(CATEGORY_ID,CATEGORY_NAME) VALUES (3,'Gaming');


--2
CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER PRIMARY KEY,
PRODUCT_NAME VARCHAR2(100) NOT NULL,
CATEGORY NUMBER, 
PRICE NUMBER DEFAULT 0 ,
STOCK_QUANTITY NUMBER DEFAULT 0 ,
--CONSTRAINT FK_CATEGORIES REFERENCES CATEGORY_ID
CONSTRAINT CATEGORY FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES(CATEGORY_ID)
);

COMMENT ON COLUMN PRODUCTS.PRODUCT_ID IS 'PRODUCT_ID' ;
COMMENT ON COLUMN PRODUCTS.PRODUCT_NAME IS 'PRODUCT_NAME' ;
COMMENT ON COLUMN PRODUCTS.CATEGORY IS 'CATEGORY';
COMMENT ON COLUMN PRODUCTS.PRICE IS 'PRICE';
COMMENT ON COLUMN PRODUCTS.STOCK_QUANTITY IS 'STOCK_QUANTITY' ;

INSERT INTO PRODUCTS.PRODUCT_ID IS 

SELECT * FROM PRODUCTS;
--3
CREATE TABLE CUSTOMERS(
CUSTOMER_ID NUMBER PRIMARY KEY,
NAME'이름'VARCHAR2(20)NOT NULL,
GENDER'성별'CHAR(3) CHECK('남','여'),
ADDRESS'주소'VARCHAR2(100),
PHONE'전화번호' VARCHAR2(30)
);

--4
CREATE TABLE ORDERS(
ORDER_ID'주문번호' NUMBER PRIMARY KEY,
ORDER_DATE'주문일' DATE[DEFAULT SYSDATE],
STATUS'처리상태'CHAR(1)[CHECK('Y','N')DEFAULT 'N'],
CUSTOMER_ID'고객ID'NUMBER [FK-CUSTOMERS(CUSTOMER_ID)ON DELETE CASCADE]
);

--5
CREATE TABLE ORDER_DETAILS(
ORDER_DETAIL_ID'주문 상세 ID'NUMBER PRIMARY KEY,
ORDER_ID '주문번호'NUMBER -[FK-ORDERS(ORDER_ID)ON DELETE CASCADE],
PRODUCT_ID'상품코드'NUMBER -[FK-PRODUCTS(PRODUCT_ID)ON DELETE SET NULL],
QUANTITY'수량' NUMBER,
PRICE_PER_UNIT'가격'NUMBER
);

